### ISSUE TITLE
cut_right not consistent

### ISSUE THREAD

**Issue by ChenfuShi** [OpenGene/fastp#131]
Hi,
I was trying to trim some next-seq data with very long low quality tails. 
I set the minimum mean quality to 25 but in the output results I still see reads that haven't been trimmed with long stretches of ////// in the quality(score=14)
Am I missing something

example:
untrimmed
@NB500968:113:HNLHTBGX7:1:11101:4491:1068 1:N:0:CGGTTA
CAGGTGTATAGTATTCAGTATATATTTTGTAAATAAAATGTTTTGTGGCTAAAAAAAAAAAAAAAAAAGAGGGGAGGGGCCCCGGGGGGGCGGCCGGGCCCGGGTGCGGGGGGGGGGGGGGGGGGGGGGGGCGAGGGGGGGGGGGGGGGGG
+
AAAAAE//EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6/////E//////A////A/<///////A/E<E<//EE//////<AE/E/E//EAA/AAA/E/<A//////////EEEAAEEA66

trimmed
@NB500968:113:HNLHTBGX7:1:11101:4491:1068:CAGGTG 1:N:0:CGGTTA
TATATATTTTGTAAATAAAATGTTTTGTGGCTAAAAAAAAAAAAAAAAAAGAGGGGAGGGGCCCCGGGGGGGCGGCCGGG
+
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE6/////E//////A////A/<///////A/E<

**Comment by sfchen** [comment]
Thanks, I will try it

**Comment by sfchen** [comment]
Reproduced, found a bug that cut right will not take effect if cut front of cut tail is not enabled.

Will fix it soon.

**Comment by sfchen** [comment]
Fixed, you can try it will the latest 0.19.7 by downloading the prebuilt binary or compiling from source.

**Comment by ChenfuShi** [comment]
Thanks! When is it going to be available on conda? Does it take a long time?

**Comment by sfchen** [comment]
May take ~10 days since I haven't released this new version

**Comment by sfchen** [comment]
0.19.7 is on conda now. please help to check and then close this issue, thanks

**Comment by ChenfuShi** [comment]
Hi,
That seems to be working fine now, But the poly A thing still seems to be not working completely. at I can still see some sequences with long polyA tails at the end of the reads or even sequences composed solely of poly As

![image](https://user-images.githubusercontent.com/40122452/53160618-3c1c6e80-35c0-11e9-822d-5441e142799c.png)


Thanks

**Comment by sfchen** [comment]
Can you close this issue, and re-open an issue about polyA problem?
